#!/bin/bash
                                                                                                                                                                                            echo -e "Counting files in the current directory - Hardcore Way\n"                                                                                                                                                                                                                                                                                                                      # Hardcore Way (Current Directory)
file_count_hardcore=$(ls -p | grep -v / | wc -l)
echo "Number of files in the current directory: $file_count_hardcore"                                                                                                                                                                                                                                                                                                                   ###################################################################################################
#                                        User Input ways                                          #                                                                                         ###################################################################################################                                                                                                                                                                                                                                                                                     #echo -e "\n#####################################################################\n"
#echo -e "Counting files in a user-specified directory - User Input Way\n"                                                                                                                                                                                                                                                                                                              #while true; do                                                                                                                                                                             #  read -p "Enter directory path (or '.' for current directory, or 'q' to quit): " user_dir
#  if [[ "$user_dir" == "q" ]]; then                                                                                                                                                        #    echo "Exiting."
#    exit 0                                                                                                                                                                                 #  fi                                                                                                                                                                                                                                                                                                                                                                                   #  if [[ -d "$user_dir" ]]; then
#    file_count_user=$(ls -p "$user_dir" | grep -v / | wc -l)                                                                                                                               #    echo "Number of files in '$user_dir': $file_count_user"
#    break # Exit after successful count (you can remove this if you want to count in multiple directories)
#  else
#    echo "Error: Directory '$user_dir' not found. Please try again."
#  fi                                                                                                                                                                                       #done                                                                                                                                                                                                                                                                                                                                                                                   #echo -e "\nScript finished." 
